# Generated by Django 4.0.4 on 2024-02-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_definition',
            name='query_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
