# Generated by Django 4.0.4 on 2024-03-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_query_definition_query_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TABLE_NAME', models.CharField(max_length=255, null=True)),
                ('COLUMN_NAME', models.CharField(max_length=255, null=True)),
                ('COLUMN_DATATYPE', models.CharField(max_length=255, null=True)),
                ('TOTAL_COUNT', models.IntegerField()),
                ('NOT_NULL_COUNT', models.IntegerField()),
                ('NULL_COUNT', models.IntegerField()),
                ('BLANK_COUNT', models.IntegerField()),
                ('DISTINCT_VALUES_COUNT', models.IntegerField()),
                ('MAX_LENGTH', models.CharField(max_length=255, null=True)),
                ('MIN_LENGTH', models.CharField(max_length=255, null=True)),
                ('MAX_VALUE', models.CharField(max_length=255, null=True)),
                ('MIN_VALUE', models.CharField(max_length=255, null=True)),
                ('NUMERIC_ONLY_VALUES_COUNT', models.IntegerField()),
                ('ALPHABETS_ONLY_VALUES_COUNT', models.IntegerField()),
                ('ALPHANUMERIC_ONLY_VALUES_COUNT', models.IntegerField()),
                ('CONTAINS_SPECIAL_CHAR_COUNT', models.IntegerField()),
                ('TOP_TEN_DISTINCT_VALUES', models.CharField(max_length=255, null=True)),
                ('TOP_TEN_DISTRIBUTED_VALUES', models.CharField(max_length=255, null=True)),
                ('RUN_DATE', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'metrics',
            },
        ),
    ]
