# Generated by Django 4.0.4 on 2024-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='query_builder_table_columns',
            name='column_data_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
